import React, { useState } from 'react';

import { Icon } from '@iconify/react';

import { PlaylistViewProvider } from '../context/PlaylistViewContext';
import ViewPlaylist from './OpenOnSpotify/ViewPlaylist';

import { useGeneralState } from '../context/generalStateContext';

function OpenOnSpotify() {
	const [openPlaylist, setOpenPlaylist] = useState(false);
	const { playListData } = useGeneralState();

	const handleClick = () => {
		setOpenPlaylist(!openPlaylist);
	};

	return (
		<>
			<div
				className={`border-brand rounded border-2 px-4 py-3 flex flex-col gap-4`}>
				<div className={`flex gap-1 ml-auto w-fit cursor-pointer`}>
					<Icon icon='solar:copy-bold' className={`h-4 w-4`} />
					<span className={`text-fxs md:text-f2xs`}>Copy Playlist Link</span>
				</div>
				<div className={`flex items-center justify-between`}>
					<div className='flex gap-1 items-center'>
						<Icon icon='logos:spotify-icon' width='30' height='30' />
						<a
							href={playListData.link}
							target='_blank'
							rel='norefferer'
							className='flex flex-col'>
							<span className={`text-fsm md:text-fxs`}>Open on Spotify</span>
							<span className='underline text-brand whitespace-normal text-fxs md:text-f2xs -mt-1 text-ellipsis'>
								Playlist generated by HearItFresh
							</span>
						</a>
					</div>
					<button
						onClick={handleClick}
						className='bg-brand rounded text-fsm px-4 py-2 text-lightest'>
						View Playlist
					</button>
				</div>
			</div>

			<PlaylistViewProvider>
				{openPlaylist && <ViewPlaylist handleClick={handleClick} />}
			</PlaylistViewProvider>
		</>
	);
};

export default OpenOnSpotify;
