import React, { useState } from 'react';

import { Icon } from '@iconify/react';
import useViewPlaylist from '../hooks/useViewPlaylist';

const OpenOnSpotify = ({ link }: { link: string }) => {
	const {
		showingTracks,
		loading,
		startedEditing,
		deleteTrack,
		restoreTracks,
		saveTracks,
	} = useViewPlaylist(link);

	const [openPlaylist, setOpenPlaylist] = useState(false);

	const handleClick = () => {
		setOpenPlaylist(!openPlaylist);
	};

	return (
		<>
			<div
				className={`border-brand rounded border-2 px-4 py-3 flex flex-col gap-4`}>
				<div className={`flex gap-1 ml-auto w-fit cursor-pointer`}>
					<Icon icon='solar:copy-bold' className={`h-4 w-4`} />
					<span className={`text-fxs md:text-f2xs`}>Copy Playlist Link</span>
				</div>
				<div className={`flex items-center justify-between`}>
					<div className='flex gap-1 items-center'>
						<Icon icon='logos:spotify-icon' width='30' height='30' />
						<a
							href={link}
							target='_blank'
							rel='norefferer'
							className='flex flex-col'>
							<span className={`text-fsm md:text-fxs`}>Open on Spotify</span>
							<span className='underline text-brand whitespace-normal text-fxs md:text-f2xs -mt-1 text-ellipsis'>
								Playlist generated by HearItFresh
							</span>
						</a>
					</div>
					<button
						onClick={handleClick}
						className='bg-brand rounded text-fsm px-4 py-2 text-lightest'>
						View Playlist
					</button>
				</div>
			</div>
			{openPlaylist && (
				<section className='mt-6 relative'>
					<div className='flex items-center justify-between sticky top-0 w-full bg-lightest dark:bg-dark text-fmd pr-2 pb-2'>
						<div className='flex items-center gap-3'>
							<button onClick={handleClick}>
								<Icon
									icon='iconoir:cancel'
									width='25'
									height='25'
									className='text-red-500'
								/>
							</button>
							<p>Playlist Generated</p>
						</div>

						{startedEditing && (
							<div className='flex items-center gap-2'>
								<button
									onClick={restoreTracks}
									className='border-brand border-2 px-4 py-1 rounded text-fbase'>
									Restore
								</button>
								<button
									onClick={saveTracks}
									disabled={loading.isLoading}
									className='bg-brand px-4 py-1 rounded text-lightest'>
									{loading.isLoading ? loading.message : 'Save'}
								</button>
							</div>
						)}
					</div>
					<ul className='flex flex-col gap-1 h-32 overflow-y-scroll '>
						{showingTracks.map(({ id, name, artist }) => {
							return (
								<li key={id} className='flex items-center gap-4'>
									<button onClick={() => deleteTrack(id)}>
										<Icon
											icon='mdi:delete'
											width='18'
											height='18'
											className='text-red-500 cursor-pointer'
										/>
									</button>
									<div className='flex items-center justify-between w-full pr-2'>
										<p>{name}</p>
										<p className='max-w-32 truncate'>{artist.join(', ')}</p>
									</div>
								</li>
							);
						})}
					</ul>
				</section>
			)}
		</>
	);
};

export default OpenOnSpotify;
