import { Icon } from '@iconify/react';
import React from 'react';

const OpenOnSpotify = ({ link }: { link: string }) => {
	return (
		<div
			className={`border-brand rounded border-2 px-4 py-3 flex flex-col gap-4`}>
			<div className={`flex gap-1 ml-auto w-fit cursor-pointer`}>
				<Icon icon='solar:copy-bold' className={`h-4 w-4`} />
				<span className={`text-fxs md:text-f2xs`}>Copy Playlist Link</span>
			</div>
			<div className={`flex gap-1 items-center`}>
				<Icon icon='logos:spotify-icon' width='30' height='30' />
				<a
					href={link}
					target='_blank'
					rel='norefferer'
					className='flex flex-col'>
					<span className={`text-fsm md:text-fxs`}>Open on Spotify</span>
					<span className='underline text-brand whitespace-normal text-fxs md:text-f2xs -mt-1 text-ellipsis'>
						Playlist generated by HearItFresh
					</span>
				</a>
			</div>
		</div>
	);
};

export default OpenOnSpotify;
