name: 🐛 Bug report

description: Report an issue to help improve the project.

title: "[BUG] <what went wrong>"

labels: ["bug"]

body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A brief description of the question or issue, including what you expected to happen and what actually happened.
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots (optional)
      description: If applicable, add screenshots that may help explain the issue.
    validations:
      required: false

  - type: textarea
    id: extrainfo
    attributes:
      label: Additional information (optional)
      description: Is there anything else we should know about this bug?
    validations:
      required: false

  - type: dropdown
    id: browser
    attributes:
      label: "🌐 Browser"
      description: "What browser did you use when you encountered the issue?"
      options:
        - Google Chrome
        - Brave
        - Microsoft Edge
        - Mozilla Firefox
        - Safari
        - Opera
        - Other
    validations:
      required: true

  - type: checkboxes
    id: no-duplicate-issues
    attributes:
      label: "🔍 Have you checked if this issue has been raised before?"
      options:
        - label: "I have checked and didn't find a similar issue"
          required: true

  - type: checkboxes
    id: read-code-of-conduct
    attributes:
      label: "🏢 Have you read and understood the Contributing Guidelines?"
      options:
        - label: "I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/HearItFresh/blob/main/CONTRIBUTING.md)"
          required: true

  - type: dropdown
    attributes:
      label: Are you willing to work on this issue?
      description: This is not required, but we are happy to guide you through the contribution process.
      options:
        - "Yes, I am willing to submit a pull request."

  - type: markdown
    attributes:
      value: |
        Follow me on Twitter [here](https://twitter.com/DunsinWebDev).
        Feel free to join the Discord server [here](https://discord.gg/kcFraw3nhz) and check out other cool repositories [here](https://github.com/Dun-sin?tab=repositories).
