name: Changelog

on:
  push:
    branches: [ main ]
  pull_request:
    branches: '*'

jobs:
  release:
    permissions:
      contents: write
      pull-requests: write
      issues: write
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    steps: 
    - uses: actions/checkout@v3
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'
    - name: Setup pnpm
      uses: pnpm/action-setup@v3
      with:
        version: 9
    - run: pnpm install --frozen-lockfile
    - run: pnpm semantic-release
      env: 
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
